spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

popq:
  auth:
    dev-login-enabled: true

  qr:
    cookie-secure: false

  seed:
    enabled: true

  push:
    firebase-enabled: ${POPQ_FIREBASE_ENABLED:false}